import http from 'node:http'; import {readFile,stat} from 'node:fs/promises'; import {extname,join,normalize} from 'node:path'; import {WebSocketServer} from 'ws'; import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../public/',import.meta.url));
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://x');let p=normalize(url.pathname).replace(/^(\.\.(\/|\\|$))+/, '');if(p==='/' )p='/index.html';let f=join(root,p);if(!(await stat(f)).isFile()) throw 0;res.writeHead(200,{'content-type':mime[extname(f)]||'application/octet-stream','cache-control':extname(f)==='.html'?'no-cache':'public,max-age=3600'});res.end(await readFile(f));}catch{res.writeHead(404);res.end('Not found');}});
const attrs=['Power','Agility','Intellect','Tech','Mystique','Charisma'];
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0} function stats(c){let x=hash(c.mint),raw=attrs.map(()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return 30+x%61}),sum=raw.reduce((a,b)=>a+b);return Object.fromEntries(attrs.map((a,i)=>[a,Math.max(25,Math.min(95,Math.round(raw[i]*360/sum)))]))} function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.random()*(i+1)|0;[a[i],a[j]]=[a[j],a[i]]}return a}
const manifest=JSON.parse(await readFile(join(root,'data/chimpions.json'),'utf8'));const cards=manifest.cards.map(c=>({...c,stats:stats(c)}));
const wss=new WebSocketServer({server,path:'/room'}),rooms=new Map();
const code=()=>Array.from({length:4},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ'[Math.random()*24|0]).join('');
function send(ws,type,data={}){if(ws.readyState===1)ws.send(JSON.stringify({type,...data}))} function peers(r){return r?.players||[]}
wss.on('connection',ws=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return} if(m.type==='create'){let c;do c=code();while(rooms.has(c));rooms.set(c,{players:[ws]});ws.room=c;send(ws,'room',{code:c,seat:0});}
else if(m.type==='join'){const c=String(m.code||'').toUpperCase(),r=rooms.get(c);if(!r||r.players.length>1)return send(ws,'error',{message:'Room unavailable'});r.players.push(ws);ws.room=c;const pool=shuffle([...cards]);r.game={decks:[pool.slice(0,6),pool.slice(6,12)],pot:[],round:1,active:Math.random()<.5?0:1,busy:false};peers(r).forEach((p,i)=>{p.seat=i;send(p,'ready',{code:c,seat:i});state(r,i)});}
else if(m.type==='action'){const r=rooms.get(ws.room),g=r?.game,a=m.action;if(!g||g.busy||ws.seat!==g.active||!attrs.includes(a))return;g.busy=true;const drawn=[g.decks[0].shift(),g.decks[1].shift()],v=drawn.map(c=>c.stats[a]);let winner=null;if(v[0]===v[1])g.pot.push(...drawn);else{winner=v[0]>v[1]?0:1;g.decks[winner].push(...drawn,...g.pot.splice(0));g.active=winner}peers(r).forEach((p,i)=>send(p,'reveal',{cards:i===0?drawn:[drawn[1],drawn[0]],values:i===0?v:[v[1],v[0]],attribute:a,winner:winner===null?null:(winner===i?'you':'them'),pot:g.pot.length}));setTimeout(()=>{g.round++;g.busy=false;if(!g.decks[0].length||!g.decks[1].length||g.round>24){const w=g.decks[0].length===g.decks[1].length?null:(g.decks[0].length>g.decks[1].length?0:1);peers(r).forEach((p,i)=>send(p,'gameover',{winner:w===null?'draw':w===i?'you':'them',counts:[g.decks[i].length,g.decks[1-i].length]}));}else peers(r).forEach((p,i)=>state(r,i));},1600);}});ws.on('close',()=>{const r=rooms.get(ws.room);if(!r)return;r.players.forEach(p=>p!==ws&&send(p,'left'));rooms.delete(ws.room);});});
function state(r,seat){const g=r.game;send(r.players[seat],'state',{card:g.decks[seat][0],counts:[g.decks[seat].length,g.decks[1-seat].length],round:g.round,pot:g.pot.length,turn:g.active===seat});}
server.listen(process.env.PORT||3000,()=>console.log(`CHIMPIONS Arena on http://localhost:${process.env.PORT||3000}`));
